# Generated by Django 2.2.6 on 2019-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='personnes',
        ),
        migrations.AlterField(
            model_name='film',
            name='annee_sortie',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
