# Generated by Django 2.2.6 on 2019-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20191125_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='annee_sortie',
        ),
        migrations.RemoveField(
            model_name='film',
            name='titre',
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='release_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
