# Generated by Django 2.2.6 on 2019-11-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20191126_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
